[package]
name = "imm-pdaf"
version = "0.1.0"
authors = ["Odin <odin@severinsen.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.23.2"
matfile = "0.2.1"